### ISSUE TITLE
IOError: Can't start download... 

### ISSUE THREAD

**Issue by lucasfagu** [jgomezdans/get_modis#11]
I am use the command of the following way:
./get_modis.py -u XXX -p XXXX -v -p MOD09A1.005 -s MOLT -y 2010 -t h13v12 -o ./ -b 1 -e 30

Traceback (most recent call last):
  File "./get_modis.py", line 342, in <module>
    get_xml=options.get_xml)
  File "./get_modis.py", line 273, in get_modisfiles
    raise IOError("Can't start download... [%s]" % the_url)
IOError: Can't start download... [http://e4ftl01.cr.usgs.gov/MOLT/MOD09A1.005//2010.01.01/MOD09A1.A2010001.h13v12.005.2010011025632.hdf]

However, when i use the link in my navigator works normally the download.

**Comment by jgomezdans** [comment]
Sorry, this is quite and old bug report and I never saw it. Apologies for that! Closing as probably not relevant.
